CREATE TABLE IF NOT EXISTS users_address (
    `key` INT,
    `properties_user_address_id` INT,
    `properties_user_address_street_address` VARCHAR(23) CHARACTER SET utf8,
    `properties_user_address_street_name` VARCHAR(19) CHARACTER SET utf8,
    `properties_user_address_street_sufix` VARCHAR(10) CHARACTER SET utf8,
    `properties_user_address_city` VARCHAR(18) CHARACTER SET utf8,
    `properties_user_address_city_prefix` VARCHAR(5) CHARACTER SET utf8,
    `properties_user_address_secondary_address` VARCHAR(9) CHARACTER SET utf8,
    `properties_user_address_address_direction` VARCHAR(9) CHARACTER SET utf8,
    `properties_user_address_state` VARCHAR(14) CHARACTER SET utf8,
    `properties_user_address_country` VARCHAR(44) CHARACTER SET utf8
);
INSERT INTO users_address VALUES (1,1,'348 Tyson Fork','Reichert Haven','Walk','South Frances','New','Apt. 581','Northeast','North Dakota','Slovenia'),
	(2,2,'426 Fausto Port','Ola Inlet','Island','Peoria','East','Suite 663','Southeast','Ohio','Egypt'),
	(3,3,'782 Koepp Lakes','Pouros Circle','Meadows','Abshirehaven','West','Suite 924','Northwest','Vermont','Niue'),
	(4,4,'637 Ana Drive','Keeley Village','Estates','San Tan Valley','East','Suite 872','Northwest','North Carolina','Ethiopia'),
	(5,5,'66651 Lang Stravenue','Rippin Cliffs','Lane','Vedafurt','Lake','Apt. 557','East','Mississippi','Antarctica (the territory South of 60 deg S)'),
	(6,6,'5039 Zion Hollow','Lind Throughway','Port','Eugene','South','Apt. 039','East','Indiana','Kiribati'),
	(7,7,'900 Roselyn Path','Ivy Knoll','Land','Domenicmouth','Lake','Apt. 281','Southeast','Mississippi','Estonia'),
	(8,8,'844 Lemuel Landing','Batz Hollow','Pine','Emileland','Lake','Suite 971','Northeast','New Jersey','Virgin Islands, U.S.'),
	(9,9,'220 Grimes Views','Pansy Spur','Mission','Claudiafort','New','Apt. 566','North','Florida','Puerto Rico'),
	(10,10,'5322 Modesta Cliff','Freddie Estates','Overpass','Sanford','Lake','Apt. 492','South','North Dakota','Central African Republic'),
	(11,11,'14613 Flatley Summit','Juanita Skyway','Lodge','Kshlerinville','New','Suite 936','Northwest','Arkansas','Uruguay'),
	(12,12,'1732 Schamberger Street','Kenyon Summit','Motorway','Lake Selina','Port','Suite 175','Northwest','Ohio','Saint Lucia'),
	(13,13,'847 Koss Meadow','Herman Drive','Mission','Linniemouth','Lake','Suite 358','Southwest','West Virginia','Estonia'),
	(14,14,'133 Nolan Street','Julio Skyway','Village','West Erin','New','Apt. 897','Southeast','Missouri','Angola'),
	(15,15,'99409 Arvel Land','Perry Lock','Islands','East Margarette','Port','Apt. 611','South','Missouri','Norfolk Island'),
	(16,16,'6195 Mariana Center','Kub Passage','Inlet','Coralietown','Lake','Apt. 071','South','Oregon','Angola'),
	(17,17,'36023 Aurelio Walk','D''Amore Hollow','Throughway','Hesperia','North','Apt. 638','Northeast','New Hampshire','Cape Verde'),
	(18,18,'215 Rowe Freeway','Bruce Mews','Grove','Lake Libby','East','Suite 805','Northeast','Arizona','Mali'),
	(19,19,'98177 Ian Spring','Gaylord Trail','Knolls','New Jackyville','New','Suite 056','Southeast','Alabama','Qatar'),
	(20,20,'2309 Larkin Oval','Spinka Greens','Wall','South Camilafort','East','Apt. 462','Southwest','Kansas','Falkland Islands (Malvinas)'),
	(21,21,'576 Walter Orchard','Halvorson Creek','Neck','New Conner','Lake','Apt. 823','East','Mississippi','Djibouti'),
	(22,22,'293 Boyle Trafficway','Holly Manor','Summit','Auermouth','North','Apt. 965','Northeast','Connecticut','French Guiana'),
	(23,23,'422 Hickle Shore','Christiansen Square','Vista','New Makenzie','New','Suite 837','East','West Virginia','Liberia'),
	(24,24,'3723 Considine Branch','Sibyl Vista','Union','East Daniela','West','Apt. 664','Southwest','Indiana','Latvia'),
	(25,25,'32273 Schowalter Fort','Adelia Ville','Plain','Schmelerville','Port','Suite 284','Northeast','Massachusetts','Tuvalu'),
	(26,26,'90030 Karen Crossing','Patrick Village','Light','Lake Madge','West','Suite 797','Southwest','Tennessee','Nepal'),
	(27,27,'157 Ruben Rapids','Hyman Valley','View','Simonisport','West','Suite 692','Northeast','Oklahoma','Bulgaria'),
	(28,28,'10123 Santa Tunnel','Caroline Extensions','Field','West Ryleehaven','East','Suite 993','North','Kansas','Lebanon'),
	(29,29,'773 Araceli Heights','Herzog Fork','Radial','Carolchester','Lake','Apt. 865','North','California','Madagascar'),
	(30,30,'430 Heathcote Roads','Jamie Course','Spring','North Armando','New','Apt. 697','North','Michigan','Algeria'),
	(31,31,'70183 Teagan Glens','Hilpert Viaduct','Village','Tyrellchester','Port','Apt. 784','West','New Hampshire','Bulgaria'),
	(32,32,'11010 Wolf Isle','Oda Centers','Landing','East Devanbury','New','Apt. 431','Southwest','Mississippi','Switzerland'),
	(33,33,'35589 Kaela Hills','McKenzie Shoals','Crossroad','Port Mistychester','Lake','Suite 405','South','Ohio','Timor-Leste'),
	(34,34,'262 Robel Trail','Alyson Spurs','Roads','West Ezra','North','Suite 559','Northwest','New Jersey','Madagascar'),
	(35,35,'18227 Cindy Unions','Anderson Ranch','Shoals','East Ezequielmouth','New','Apt. 916','Northeast','Wyoming','Mozambique'),
	(36,36,'745 Eino Island','Adela Trace','Prairie','Meridian','South','Suite 538','Southwest','Alabama','Philippines'),
	(37,37,'458 Leola Key','Miller Row','Wall','North Conor','South','Suite 434','West','Kentucky','Greece'),
	(38,38,'4198 Moore Oval','McKenzie Tunnel','Station','Laurineport','New','Suite 102','Southeast','Mississippi','Croatia'),
	(39,39,'231 Marjorie Ferry','Funk Branch','Springs','Jamaalshire','South','Suite 698','Northeast','California','Saint Lucia'),
	(40,40,'976 Major Street','Rocio Ramp','Roads','Selenashire','Port','Suite 556','Northwest','Wyoming','Macao'),
	(41,41,'7617 Klocko Via','Oren Prairie','Drives','Wheaton','New','Apt. 654','Northeast','Minnesota','Virgin Islands, British'),
	(42,42,'7419 Beier Inlet','Grant Roads','Crossroad','Maximemouth','Lake','Suite 669','North','Maryland','Dominica'),
	(43,43,'486 Abshire Shore','Waters Camp','Ridge','Nadershire','Lake','Apt. 009','Northwest','Wyoming','Sweden'),
	(44,44,'61019 Darlene Wells','Sonia Lock','Glens','Coychester','West','Suite 343','Southeast','Texas','Kenya'),
	(45,45,'6413 Sofia Way','Yundt Park','Stream','West Otto','New','Apt. 371','North','New York','Panama'),
	(46,46,'40032 Otho Mountains','Angus Plain','Springs','Armstrongfurt','South','Apt. 338','Southeast','Hawaii','Holy See (Vatican City State)'),
	(47,47,'4772 Dolores Route','Murphy Squares','Crescent','Kenyatown','Lake','Apt. 767','North','South Carolina','Mayotte'),
	(48,48,'6525 Thompson Stravenue','Jacobi Villages','Turnpike','Kraigshire','East','Apt. 197','East','Arkansas','Thailand'),
	(49,49,'3889 Lindsay Haven','O''Hara Squares','Pass','East Lemuelport','West','Apt. 894','East','Louisiana','Samoa'),
	(50,50,'4046 Precious Plains','Shanahan Trace','Radial','South Jonathan','South','Suite 299','Southwest','Oregon','Guam'),
	(51,51,'9300 Kacey Island','Schimmel Valley','Ports','O''Connerberg','Lake','Apt. 212','Northwest','Ohio','Vietnam'),
	(52,52,'058 Cormier Tunnel','Sandra Roads','Gateway','Framiborough','New','Suite 829','North','North Dakota','Bhutan'),
	(53,53,'9861 Franecki Crossing','Waters Ferry','Circle','Loveland','Port','Suite 615','North','Rhode Island','Switzerland'),
	(54,54,'410 Rolfson Road','Vernon Points','Motorway','East Dorcasborough','South','Suite 833','East','Kentucky','Faroe Islands'),
	(55,55,'9100 Heaney Lakes','Wilkinson Summit','Overpass','South Hank','North','Suite 585','Southwest','Oklahoma','Lao People''s Democratic Republic'),
	(56,56,'304 Keeling Rue','Garth Flat','Stream','Everett','West','Apt. 075','East','Wisconsin','Jordan'),
	(57,57,'27379 Kaylee Island','Deangelo Grove','Valleys','Miaport','West','Suite 846','Southwest','Missouri','Macedonia'),
	(58,58,'53872 Matteo Wells','Audra Mews','Neck','East Abigailview','North','Suite 210','East','New Hampshire','Croatia'),
	(59,59,'405 Bauch Pike','Gina Ports','Island','Gardena','West','Suite 464','Southwest','North Dakota','Peru'),
	(60,60,'81296 Batz Fort','Virginia Mountain','Passage','Roycemouth','South','Apt. 831','East','Mississippi','Bolivia'),
	(61,61,'50048 Considine Pike','Aurore Ville','Manor','Port Janniechester','Lake','Suite 393','South','North Carolina','Argentina'),
	(62,62,'9044 Armstrong Trail','Schimmel Village','Shores','South Bernardofort','Port','Apt. 904','Southeast','Missouri','Montserrat'),
	(63,63,'7528 Angelita Springs','Myrl Locks','Vista','Port Keaton','South','Apt. 173','Northwest','Hawaii','Poland'),
	(64,64,'5645 Maximus Corners','Littel Corners','Mountain','Maribelborough','South','Suite 054','Southeast','Vermont','Bahamas'),
	(65,65,'1726 Henderson Valley','Emiliano Harbors','Harbor','South Imatown','Lake','Suite 708','Southwest','New Jersey','Lao People''s Democratic Republic'),
	(66,66,'1400 Osborne Plains','Ruecker Tunnel','Square','New Miguel','Lake','Suite 403','East','Louisiana','Svalbard & Jan Mayen Islands'),
	(67,67,'64125 Xavier Views','Bauch Dale','Greens','New Zena','West','Suite 564','Northeast','Arizona','New Zealand'),
	(68,68,'5393 Gloria Glens','Annalise Plains','Plaza','Raynorview','South','Suite 744','South','Massachusetts','Malta'),
	(69,69,'927 Antwon Track','Elwin Common','Park','Cornellfurt','Lake','Apt. 391','Southeast','North Carolina','Micronesia'),
	(70,70,'3030 Donny Way','Erik Vista','Lodge','Lakewood','New','Suite 447','Southwest','Georgia','Australia'),
	(71,71,'75526 Sven Bridge','Stephan Estate','Gateway','Detroit','West','Apt. 234','East','Arkansas','Puerto Rico'),
	(72,72,'18847 Reynolds Spur','Heller Forks','Lane','Bernadinehaven','East','Apt. 153','Northeast','Mississippi','Croatia'),
	(73,73,'853 Lily Ports','Adams Haven','Station','Sincereberg','East','Suite 145','Southeast','Wisconsin','Samoa'),
	(74,74,'90513 Marcelle Hills','Gulgowski Trail','Flats','New Raeside','North','Apt. 740','Northwest','Delaware','Bhutan'),
	(75,75,'5795 Shields Villages','Kasey Trafficway','Lights','Fremont','East','Apt. 243','West','Arizona','Aruba'),
	(76,76,'817 Ziemann Greens','Assunta Path','Courts','East Dorthachester','East','Suite 019','West','New York','Tajikistan'),
	(77,77,'884 Padberg Views','Dare Cape','Heights','Paucektown','New','Suite 333','East','Alabama','Guadeloupe'),
	(78,78,'7356 Demario Lake','Lakin Vista','River','Theodoraville','Port','Apt. 271','South','Virginia','Panama'),
	(79,79,'313 Joaquin Green','Marilie Mews','Wall','Brigitteborough','West','Apt. 472','Northeast','Utah','Ecuador'),
	(80,80,'55173 Hayes Key','Baron Ford','Mountain','Joplin','North','Suite 292','South','South Carolina','Botswana'),
	(81,81,'3633 Shanahan Harbors','Nikolaus Manor','Field','Stoneborough','Port','Suite 465','South','Tennessee','Northern Mariana Islands'),
	(82,82,'83412 Rogahn Meadow','Larson Knolls','Junction','Twin Falls','South','Apt. 631','East','Louisiana','El Salvador'),
	(83,83,'041 Aimee Square','Kiara Flats','Drives','Lefflermouth','West','Apt. 995','Northwest','Oklahoma','India'),
	(84,84,'9638 Skiles Vista','Koss Fork','Forks','West Desiree','East','Apt. 004','East','New York','Bangladesh'),
	(85,85,'375 Sven Lake','Heathcote Landing','Hill','Port Olga','South','Apt. 154','North','Oregon','Austria'),
	(86,86,'0470 Magnolia Lake','Estevan Ville','Springs','North Keegan','South','Suite 386','Northeast','Kentucky','Croatia'),
	(87,87,'769 Veum Brook','Anjali Estate','Squares','Macton','Port','Apt. 554','South','Maine','Turks and Caicos Islands'),
	(88,88,'4351 Sigurd Crescent','Johann Causeway','Lake','Lenexa','East','Apt. 772','Northeast','Texas','Pitcairn Islands'),
	(89,89,'225 Branson Fields','Eduardo Keys','Springs','Peoria','West','Suite 638','Southeast','Pennsylvania','Suriname'),
	(90,90,'279 Treutel Drive','Lulu Harbor','Islands','New Belleville','Lake','Suite 113','West','New Mexico','Iceland'),
	(91,91,'2270 Tiana Harbor','Erdman Ports','Dam','East Nevaside','New','Suite 361','North','New Hampshire','Vanuatu'),
	(92,92,'940 Wiza Loaf','Carolyne Springs','Common','Hackettport','Lake','Suite 455','East','Virginia','Azerbaijan'),
	(93,93,'88634 Queenie Path','Lubowitz Roads','Meadow','New Rodrigohaven','East','Suite 541','Southeast','Massachusetts','Uganda'),
	(94,94,'15837 Mathilde Camp','Zack Mission','Orchard','South Mariellefort','Lake','Apt. 262','Southeast','Idaho','Latvia'),
	(95,95,'53538 Whitney Isle','Raheem Crest','Light','Hendersonville','East','Apt. 588','Northeast','Ohio','Malta'),
	(96,96,'7421 Thea Manors','Sydnee Center','Port','Legrosside','East','Apt. 999','North','Indiana','Western Sahara'),
	(97,97,'93723 Gleichner Plains','O''Reilly Crossing','Mall','East Kirstenland','East','Apt. 942','Southeast','Maryland','Mauritius'),
	(98,98,'260 Enid Rue','Rempel Place','Curve','Jacobiborough','West','Apt. 447','Southeast','South Dakota','Dominica'),
	(99,99,'662 Kamryn Stravenue','Zulauf Mews','Spring','Hermistonberg','West','Apt. 457','Southwest','Hawaii','Isle of Man'),
	(100,100,'8314 Sam Hills','Swift Drive','Forest','West Allene','South','Suite 729','Southeast','South Dakota','Dominican Republic');
